# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@1.3.0
workflows:
  publish:
    jobs:
      - docker/publish:
          image: robertmccausland4/kubenator
          dockerfile: dockerfile
          tag: latest
